package net.watchbox.global.tmdb.configuration;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * TMDB 가 응답 키로 사용하는 국가 코드 (ISO 3166-1 alpha-2).
 * 영문명/한글명 매핑 + Jackson 직렬화/역직렬화 지원.
 * TMDB Configuration > Countries API 응답 기준 전체 목록 (englishValue 는 TMDB english_name 사용).
 */
@Getter
@AllArgsConstructor
public enum Country {
    AD("Andorra", "안도라"),
    AE("United Arab Emirates", "아랍에미리트"),
    AF("Afghanistan", "아프가니스탄"),
    AG("Antigua and Barbuda", "앤티가 바부다"),
    AI("Anguilla", "앵귈라"),
    AL("Albania", "알바니아"),
    AM("Armenia", "아르메니아"),
    AN("Netherlands Antilles", "네덜란드령 앤틸리스"),
    AO("Angola", "앙골라"),
    AQ("Antarctica", "남극"),
    AR("Argentina", "아르헨티나"),
    AS("American Samoa", "아메리칸 사모아"),
    AT("Austria", "오스트리아"),
    AU("Australia", "호주"),
    AW("Aruba", "아루바"),
    AZ("Azerbaijan", "아제르바이잔"),
    BA("Bosnia and Herzegovina", "보스니아 헤르체고비나"),
    BB("Barbados", "바베이도스"),
    BD("Bangladesh", "방글라데시"),
    BE("Belgium", "벨기에"),
    BF("Burkina Faso", "부르키나파소"),
    BG("Bulgaria", "불가리아"),
    BH("Bahrain", "바레인"),
    BI("Burundi", "부룬디"),
    BJ("Benin", "베냉"),
    BM("Bermuda", "버뮤다"),
    BN("Brunei Darussalam", "브루나이"),
    BO("Bolivia", "볼리비아"),
    BR("Brazil", "브라질"),
    BS("Bahamas", "바하마"),
    BT("Bhutan", "부탄"),
    BU("Burma", "버마"),
    BV("Bouvet Island", "부베섬"),
    BW("Botswana", "보츠와나"),
    BY("Belarus", "벨라루스"),
    BZ("Belize", "벨리즈"),
    CA("Canada", "캐나다"),
    CC("Cocos Islands", "코코스 제도"),
    CD("Congo", "콩고 민주공화국"),
    CF("Central African Republic", "중앙아프리카 공화국"),
    CG("Congo", "콩고 공화국"),
    CH("Switzerland", "스위스"),
    CI("Cote D'Ivoire", "코트디부아르"),
    CK("Cook Islands", "쿡 제도"),
    CL("Chile", "칠레"),
    CM("Cameroon", "카메룬"),
    CN("China", "중국"),
    CO("Colombia", "콜롬비아"),
    CR("Costa Rica", "코스타리카"),
    CS("Serbia and Montenegro", "세르비아 몬테네그로"),
    CU("Cuba", "쿠바"),
    CV("Cape Verde", "카보베르데"),
    CX("Christmas Island", "크리스마스섬"),
    CY("Cyprus", "키프로스"),
    CZ("Czech Republic", "체코"),
    DE("Germany", "독일"),
    DJ("Djibouti", "지부티"),
    DK("Denmark", "덴마크"),
    DM("Dominica", "도미니카"),
    DO("Dominican Republic", "도미니카 공화국"),
    DZ("Algeria", "알제리"),
    EC("Ecuador", "에콰도르"),
    EE("Estonia", "에스토니아"),
    EG("Egypt", "이집트"),
    EH("Western Sahara", "서사하라"),
    ER("Eritrea", "에리트레아"),
    ES("Spain", "스페인"),
    ET("Ethiopia", "에티오피아"),
    FI("Finland", "핀란드"),
    FJ("Fiji", "피지"),
    FK("Falkland Islands", "포클랜드 제도"),
    FM("Micronesia", "미크로네시아"),
    FO("Faeroe Islands", "페로 제도"),
    FR("France", "프랑스"),
    GA("Gabon", "가봉"),
    GB("United Kingdom", "영국"),
    GD("Grenada", "그레나다"),
    GE("Georgia", "조지아"),
    GF("French Guiana", "프랑스령 기아나"),
    GH("Ghana", "가나"),
    GI("Gibraltar", "지브롤터"),
    GL("Greenland", "그린란드"),
    GM("Gambia", "감비아"),
    GN("Guinea", "기니"),
    GP("Guadaloupe", "과들루프"),
    GQ("Equatorial Guinea", "적도 기니"),
    GR("Greece", "그리스"),
    GS("South Georgia and the South Sandwich Islands", "사우스조지아 사우스샌드위치 제도"),
    GT("Guatemala", "과테말라"),
    GU("Guam", "괌"),
    GW("Guinea-Bissau", "기니비사우"),
    GY("Guyana", "가이아나"),
    HK("Hong Kong", "홍콩"),
    HM("Heard and McDonald Islands", "허드 맥도널드 제도"),
    HN("Honduras", "온두라스"),
    HR("Croatia", "크로아티아"),
    HT("Haiti", "아이티"),
    HU("Hungary", "헝가리"),
    ID("Indonesia", "인도네시아"),
    IE("Ireland", "아일랜드"),
    IL("Israel", "이스라엘"),
    IN("India", "인도"),
    IO("British Indian Ocean Territory", "영국령 인도양 지역"),
    IQ("Iraq", "이라크"),
    IR("Iran", "이란"),
    IS("Iceland", "아이슬란드"),
    IT("Italy", "이탈리아"),
    JM("Jamaica", "자메이카"),
    JO("Jordan", "요르단"),
    JP("Japan", "일본"),
    KE("Kenya", "케냐"),
    KG("Kyrgyz Republic", "키르기스스탄"),
    KH("Cambodia", "캄보디아"),
    KI("Kiribati", "키리바시"),
    KM("Comoros", "코모로"),
    KN("St. Kitts and Nevis", "세인트키츠 네비스"),
    KP("North Korea", "북한"),
    KR("South Korea", "한국"),
    KW("Kuwait", "쿠웨이트"),
    KY("Cayman Islands", "케이맨 제도"),
    KZ("Kazakhstan", "카자흐스탄"),
    LA("Lao People's Democratic Republic", "라오스"),
    LB("Lebanon", "레바논"),
    LC("St. Lucia", "세인트루시아"),
    LI("Liechtenstein", "리히텐슈타인"),
    LK("Sri Lanka", "스리랑카"),
    LR("Liberia", "라이베리아"),
    LS("Lesotho", "레소토"),
    LT("Lithuania", "리투아니아"),
    LU("Luxembourg", "룩셈부르크"),
    LV("Latvia", "라트비아"),
    LY("Libyan Arab Jamahiriya", "리비아"),
    MA("Morocco", "모로코"),
    MC("Monaco", "모나코"),
    MD("Moldova", "몰도바"),
    ME("Montenegro", "몬테네그로"),
    MG("Madagascar", "마다가스카르"),
    MH("Marshall Islands", "마셜 제도"),
    MK("Macedonia", "마케도니아"),
    ML("Mali", "말리"),
    MM("Myanmar", "미얀마"),
    MN("Mongolia", "몽골"),
    MO("Macao", "마카오"),
    MP("Northern Mariana Islands", "북마리아나 제도"),
    MQ("Martinique", "마르티니크"),
    MR("Mauritania", "모리타니"),
    MS("Montserrat", "몬트세랫"),
    MT("Malta", "몰타"),
    MU("Mauritius", "모리셔스"),
    MV("Maldives", "몰디브"),
    MW("Malawi", "말라위"),
    MX("Mexico", "멕시코"),
    MY("Malaysia", "말레이시아"),
    MZ("Mozambique", "모잠비크"),
    NA("Namibia", "나미비아"),
    NC("New Caledonia", "뉴칼레도니아"),
    NE("Niger", "니제르"),
    NF("Norfolk Island", "노퍽섬"),
    NG("Nigeria", "나이지리아"),
    NI("Nicaragua", "니카라과"),
    NL("Netherlands", "네덜란드"),
    NO("Norway", "노르웨이"),
    NP("Nepal", "네팔"),
    NR("Nauru", "나우루"),
    NU("Niue", "니우에"),
    NZ("New Zealand", "뉴질랜드"),
    OM("Oman", "오만"),
    PA("Panama", "파나마"),
    PE("Peru", "페루"),
    PF("French Polynesia", "프랑스령 폴리네시아"),
    PG("Papua New Guinea", "파푸아뉴기니"),
    PH("Philippines", "필리핀"),
    PK("Pakistan", "파키스탄"),
    PL("Poland", "폴란드"),
    PM("St. Pierre and Miquelon", "생피에르 미클롱"),
    PN("Pitcairn Island", "핏케언 제도"),
    PR("Puerto Rico", "푸에르토리코"),
    PS("Palestinian Territory", "팔레스타인"),
    PT("Portugal", "포르투갈"),
    PW("Palau", "팔라우"),
    PY("Paraguay", "파라과이"),
    QA("Qatar", "카타르"),
    RE("Reunion", "레위니옹"),
    RO("Romania", "루마니아"),
    RS("Serbia", "세르비아"),
    RU("Russia", "러시아"),
    RW("Rwanda", "르완다"),
    SA("Saudi Arabia", "사우디아라비아"),
    SB("Solomon Islands", "솔로몬 제도"),
    SC("Seychelles", "세이셸"),
    SD("Sudan", "수단"),
    SE("Sweden", "스웨덴"),
    SG("Singapore", "싱가포르"),
    SH("St. Helena", "세인트헬레나"),
    SI("Slovenia", "슬로베니아"),
    SJ("Svalbard & Jan Mayen Islands", "스발바르 얀마옌"),
    SK("Slovakia", "슬로바키아"),
    SL("Sierra Leone", "시에라리온"),
    SM("San Marino", "산마리노"),
    SN("Senegal", "세네갈"),
    SO("Somalia", "소말리아"),
    SR("Suriname", "수리남"),
    SS("South Sudan", "남수단"),
    ST("Sao Tome and Principe", "상투메 프린시페"),
    SU("Soviet Union", "소비에트 연방"),
    SV("El Salvador", "엘살바도르"),
    SY("Syrian Arab Republic", "시리아"),
    SZ("Swaziland", "에스와티니"),
    TC("Turks and Caicos Islands", "터크스 케이커스 제도"),
    TD("Chad", "차드"),
    TF("French Southern Territories", "프랑스령 남방 및 남극 지역"),
    TG("Togo", "토고"),
    TH("Thailand", "태국"),
    TJ("Tajikistan", "타지키스탄"),
    TK("Tokelau", "토켈라우"),
    TL("Timor-Leste", "동티모르"),
    TM("Turkmenistan", "투르크메니스탄"),
    TN("Tunisia", "튀니지"),
    TO("Tonga", "통가"),
    TP("East Timor", "동티모르"),
    TR("Turkey", "튀르키예"),
    TT("Trinidad and Tobago", "트리니다드 토바고"),
    TV("Tuvalu", "투발루"),
    TW("Taiwan", "대만"),
    TZ("Tanzania", "탄자니아"),
    UA("Ukraine", "우크라이나"),
    UG("Uganda", "우간다"),
    UM("United States Minor Outlying Islands", "미국령 군소 제도"),
    US("United States of America", "미국"),
    UY("Uruguay", "우루과이"),
    UZ("Uzbekistan", "우즈베키스탄"),
    VA("Holy See", "바티칸 시국"),
    VC("St. Vincent and the Grenadines", "세인트빈센트 그레나딘"),
    VE("Venezuela", "베네수엘라"),
    VG("British Virgin Islands", "영국령 버진아일랜드"),
    VI("US Virgin Islands", "미국령 버진아일랜드"),
    VN("Vietnam", "베트남"),
    VU("Vanuatu", "바누아투"),
    WF("Wallis and Futuna Islands", "왈리스 푸투나"),
    WS("Samoa", "사모아"),
    XC("Czechoslovakia", "체코슬로바키아"),
    XG("East Germany", "동독"),
    XI("Northern Ireland", "북아일랜드"),
    XK("Kosovo", "코소보"),
    YE("Yemen", "예멘"),
    YT("Mayotte", "마요트"),
    YU("Yugoslavia", "유고슬라비아"),
    ZA("South Africa", "남아프리카 공화국"),
    ZM("Zambia", "잠비아"),
    ZR("Zaire", "자이르"),
    ZW("Zimbabwe", "짐바브웨");

    private final String englishValue;
    private final String koreanValue;

    private static final Map<String, Country> BY_CODE =
            Arrays.stream(values())
                    .collect(Collectors.toMap(Enum::name, c -> c));

    /**
     * 직렬화 시 ISO 코드(enum 이름)를 그대로 사용. 예: KR, US, JP
     */
    @JsonValue
    public String toJson() {
        return name();
    }

    /**
     * 역직렬화: ISO 코드로 enum 매칭. 알 수 없는 코드면 null 반환 (예외 발생 X).
     */
    @JsonCreator
    public static Country fromCode(String code) {
        if (code == null) {
            return null;
        }
        return BY_CODE.get(code);
    }

    public static String getKoreanByCode(String code) {
        Country c = BY_CODE.get(code);
        return c != null ? c.koreanValue : null;
    }

    public static String getEnglishByCode(String code) {
        Country c = BY_CODE.get(code);
        return c != null ? c.englishValue : null;
    }
}
