server:
  port: 9000

spring:
  application:
    name: watchbox-local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/watchbox?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 95206326

  web:
    resources:
      add-mappings: false # 정적 리소스 자동 매핑 비활성화하여 예외(NoHandlerFoundException) 발생시키기 위함

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 368529952006-3pjat35sq8k6bco7mvrf1kt43ttsdml7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

tmdb:
  api:
    key: 7a71b03109fd04667129147735ca6ff5
    base-url: https://api.themoviedb.org/3
  image-url: https://image.tmdb.org/t/p/w500

url:
    frontend:
        local-main: http://localhost:3000
        local-sub: http://localhost:4000
        domain: https://www.watch-box.net
    backend:
        local: http://localhost:9000
#        domain: https://api.watch-box.net

jwt:
    issuer: watchbox-net@gmail.com
    secret_key: watchbox-net-secret-key
    refresh_token_expiry: 7d
    access_token_expiry: 1h

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    doc-expansion: none
    persist-authorization: true
    tags-sorter: alpha