server:
  port: 9000

spring:
  application:
    name: watchbox-local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/watchbox?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 95206326

  web:
    resources:
      add-mappings: false # 정적 리소스 자동 매핑 비활성화하여 예외(NoHandlerFoundException) 발생시키기 위함

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile

tmdb:
  api:
    key: ${TMDB_API_KEY}
    base-url: https://api.themoviedb.org/3
  image-url: https://image.tmdb.org/t/p/w500

url:
  frontend: ${URL_FRONTEND:http://localhost:3000}
#  backend:  ${URL_BACKEND:http://localhost:9000}

jwt:
  issuer: ${JWT_ISSUER:abc}
  secret_key: ${JWT_SECRET_KEY:abcdefgh1234567890}
  refresh_token_expiry: 7d
  access_token_expiry: 3h

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    doc-expansion: none
    persist-authorization: true
    tags-sorter: alpha