server:
  port: 8080

logging:                                         # ← 여기. 최상위
  level:
    root: INFO
    net.watchbox: DEBUG
    org.springframework.web: DEBUG               # HTTP 요청/응답
#    org.hibernate.SQL: DEBUG                     # SQL 쿼리 (선택)
#    org.hibernate.orm.jdbc.bind: TRACE           # SQL 파라미터 (너무 noisy)