server:
  port: 8080

spring:
  application:
    name: watchbox

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

management:
  tracing:
    sampling:
      probability: 0.1  # prod: 10% 샘플링 (비용/성능 고려)

jwt:
  refresh_token_expiry: 7d
  access_token_expiry: 1h

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
