name: Backend CI/CD Dev

on:
  push:
    branches:
      - dev

env:
  APP_NAME: watchbox-be
  DOCKER_IMAGE: watchbox-be:latest

jobs:
  build:
    runs-on: [self-hosted, dev, backend]
    environment: development

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -f Dockerfile -t ${{ env.DOCKER_IMAGE }} .

      - name: Create .env file for Docker
        run: |
          cat <<'EOF' > watchbox-dev-be.env
          SPRING_PROFILES_ACTIVE=dev
          DB_URL=${{ secrets.DB_URL }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Run docker container on watchbox-dev server
        run: |
          docker stop ${{ env.APP_NAME }} || true
          docker rm -f ${{ env.APP_NAME }} || true
          docker run -d \
            --name ${{ env.APP_NAME }} \
            --env-file ./watchbox-dev-be.env \
            --network watchbox-net \
            -p 8080:8080 \
#            -v /home/ubuntu/backup/spring-boot/logs:/app/logs \
            ${{ env.DOCKER_IMAGE }}
          docker image prune -f
